User Management Validation
ICTD-Sorsogon/DocTrack pull request #102
Opened 2021-03-23 00:29 UTC by kennethsolomon

2021-03-24 01:47 UTC, snretuerma requested changes
Form for User Management radio buttons

2021-03-24 01:53 UTC, paulbryandy reviewed
LGMT

2021-03-24 01:53 UTC, paulbryandy commented on app/Listeners/NotificationListener.php
> +            dd($doc->tracking_code);
Remove dd

2021-03-26 03:25 UTC, snretuerma approved these changes

2021-03-26 03:26 UTC, merged