Login Controller
ICTD-Sorsogon/DocTrack pull request #31
Opened 2021-01-28 00:45 UTC by synecders

2021-01-28 08:54 UTC, snretuerma requested changes
Add formatting on the login form error notification

2021-02-01 05:21 UTC, JPGrefaldo approved these changes

2021-02-01 06:04 UTC, snretuerma requested changes
Remove duplicate dialog for empty values

2021-02-05 06:39 UTC, JPGrefaldo approved these changes

2021-02-05 06:45 UTC, JPGrefaldo approved these changes

2021-02-05 06:45 UTC, merged